trigger:
- main

resources:
- repo: self

variables:
  unitTest: '$(System.DefaultWorkingDirectory)/BlogPetNews.Unit.Tests/BlogPetNews.Unit.Tests.csproj'
  integrationTest: '$(System.DefaultWorkingDirectory)/BlogPetNews.Integration.Tests/BlogPetNews.Integration.Tests.csproj'
  api: '$(System.DefaultWorkingDirectory)/BlogPetNews.API/BlogPetNews.API.csproj'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Restore
    displayName: 'Restore dependencies'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet restore $(api)
      displayName: 'Restore dependencies'
  - job: Build
    displayName: 'Build'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet run $(api) --configuration Release
      displayName: 'Build'

- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: UnitTests
    displayName: 'Run Unit Tests'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet test $(unitTeste) --configuration Release
      displayName: 'Run Unit Tests'
  - job: IntegrationTests
    displayName: 'Run Integration Tests'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet test $(integrationTeste) --configuration Release
      displayName: 'Run Integration Tests'
